# supabase/config.toml

config_version = "1"
project_id = "gunpla-stock-bot"

[api]
# API port when running `supabase start`
port = 8000

[db]
# Port to use for the local database
port = 5432

[functions]
  [functions.line-webhook]
    # Environment variables that will be applied to the function
    # when running `supabase functions serve`
    # env_file = ".env.local"
    # import_map = "supabase/functions/import_map.json"
